### PR TITLE
Add `@deparse` macro

### LINKED ISSUE #59: re-create PR
However, I need to re-create another pull request because of the name of the branch contains "inst". No worry, It's a piece of cake. I will do that.

_Originally posted by @terasakisatoshi in https://github.com/AtelierArith/Replay.jl/pull/56#discussion_r1164829316_

### PR DESCRIPTION
**Pull request by hyrodium**
This PR fixes #59, closes #56.

### CODE REVIEW

**Comment by hyrodium** [comment]
Hmm, not sure why [the doctest fails](https://github.com/AtelierArith/Replay.jl/actions/runs/6535084230/job/17896496224?pr=72)..

```julia
julia> using Replay
[ Info: Precompiling Replay [dd78c5bf-19c4-4e9c-96ce-c3ec745c7812]

julia> @deparse 1+1
"1 + 1"

julia> @deparse sin(1f0+a)
"sin(1.0f0 + a)"

julia> @deparse f(x) = sin(x)/x  # Sometimes not work as expected
"f(x) = begin\n        sin(x) / x\n    end\n"

julia> versioninfo()
Julia Version 1.9.3
Commit bed2cd540a1 (2023-08-24 14:43 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 16 × AMD Ryzen 7 2700X Eight-Core Processor
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, znver1)
  Threads: 1 on 16 virtual cores
```

EDIT: I was forgetting to add `@doc raw"..."` to the docstring. I was confused because `doctest(Replay, fix=true)`does not fix the problem.

**Comment by terasakisatoshi** [comment]
@hyrodium How about `\\n`?

image



```console
 julia --project=docs -e '
            using Documenter: DocMeta, doctest
            using Replay
            DocMeta.setdocmeta!(Replay, :DocTestSetup, :(using Replay); recursive=true)
            doctest(Replay)'
```

image

**Comment by terasakisatoshi** [comment]
nvm...

b0063c4 looks good to me

**Comment by terasakisatoshi** [comment]
🎉

**Pull request merged**
